# General command in Numpy and Pandas

## If, else, elif

In [3]:
the_3_musketeers = ('Athos', 'Porthos', 'Aramis')

a_candidate = "D'Artagnan"

if a_candidate in the_3_musketeers:
    print("{} is a musketeer".format(a_candidate))
else:
    print("{} is not a musketeer".format(a_candidate))

D'Artagnan is not a musketeer


In [5]:
a_number = 15

if a_number % 2 == 0:
    print('{} is divisible by 2'.format(a_number))
elif a_number % 3 == 0:
    print('{} is divisible by 3'.format(a_number))
elif a_number % 5 == 0:
    print('{} is divisible by 5'.format(a_number))
elif a_number % 7 == 0:
    print('{} is divisible by 7'.format(a_number))

15 is divisible by 3


In [6]:
a_number = 15

if a_number % 2 == 0:
    print("{} is even".format(a_number))
    if a_number % 3 == 0:
        print("{} is also divisible by 3".format(a_number))
    else:
        print("{} is not divisible by 3".format(a_number))
else:
    print("{} is odd".format(a_number))
    if a_number % 5 == 0:
        print("{} is also divisible by 5".format(a_number))
    else:
        print("{} is not divisible by 5".format(a_number))

15 is odd
15 is also divisible by 5


## while loop

In [7]:
i = 1
result = 1

while i <= 100:
    result *= i
    if i == 42:
        print('Magic number 42 reached! Stopping execution..')
        break
    i += 1
    
print('i:', i)
print('result:', result)

Magic number 42 reached! Stopping execution..
i: 42
result: 1405006117752879898543142606244511569936384000000000


In [8]:
i = 1
result = 1

while i < 20:
    i += 1
    if i % 2 == 0:
        print('Skipping {}'.format(i))
        continue
    print('Multiplying with {}'.format(i))
    result = result * i
    
print('i:', i)
print('result:', result)

Skipping 2
Multiplying with 3
Skipping 4
Multiplying with 5
Skipping 6
Multiplying with 7
Skipping 8
Multiplying with 9
Skipping 10
Multiplying with 11
Skipping 12
Multiplying with 13
Skipping 14
Multiplying with 15
Skipping 16
Multiplying with 17
Skipping 18
Multiplying with 19
Skipping 20
i: 20
result: 654729075


## for loop

In [10]:
# Looping over a string
for char in 'Monday':
    print(char)

M
o
n
d
a
y


In [11]:
# Looping over a tuple
for fruit in ('Apple', 'Banana', 'Guava'):
    print("Here's a fruit:", fruit)

Here's a fruit: Apple
Here's a fruit: Banana
Here's a fruit: Guava


In [12]:
# Looping over a dictionary
person = {
    'name': 'John Doe',
    'sex': 'Male',
    'age': 32,
    'married': True
}

for key in person:
    print("Key:", key, ",", "Value:", person[key])

Key: name , Value: John Doe
Key: sex , Value: Male
Key: age , Value: 32
Key: married , Value: True


In [13]:
# Looping over a list

a_list = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday']

for i in range(len(a_list)):
    print('The value at position {} is {}.'.format(i, a_list[i]))

The value at position 0 is Monday.
The value at position 1 is Tuesday.
The value at position 2 is Wednesday.
The value at position 3 is Thursday.
The value at position 4 is Friday.


## Example:

In [15]:
#Suppose we want to use climate data like the temperature, rainfall, and humidity to determine if a region is well suited for growing apples.
#A simple approach for doing this would be to formulate the relationship between the annual yield of apples (tons per hectare) and the climatic conditions
#like the average temperature (in degrees Fahrenheit), rainfall (in millimeters) & average relative humidity (in percentage) as a linear equation.

#yield_of_apples = w1 * temperature + w2 * rainfall + w3 * humidity

In [17]:
w1, w2, w3 = 0.3, 0.2, 0.5

#To make it slightly easier to perform the above computation for multiple regions, we can represent the climate data for each region as a vector, i.e., a list of numbers.

kanto = [73, 67, 43]
johto = [91, 88, 64]
hoenn = [87, 134, 58]
sinnoh = [102, 43, 37]
unova = [69, 96, 70]

weights = [w1, w2, w3]

# We can now write a function crop_yield to calcuate the yield of apples (or any other crop) given the climate data and the respective weights.

def crop_yield(region, weights):
    result = 0
    for x, w in zip(region, weights):
        result += x * w
    return result
crop_yield(kanto, weights)

56.8

# Going from Python lists to Numpy arrays


## Let's import the Numpy library.



In [23]:
import numpy as np

In [24]:
#Suppose we want to use climate data like the temperature, rainfall, and humidity to determine if a region is well suited for growing apples.
#A simple approach for doing this would be to formulate the relationship between the annual yield of apples (tons per hectare) and the climatic conditions
#like the average temperature (in degrees Fahrenheit), rainfall (in millimeters) & average relative humidity (in percentage) as a linear equation.

#yield_of_apples = w1 * temperature + w2 * rainfall + w3 * humidity

In [25]:
kanto = np.array([73, 67, 43])
weights = np.array([0.3, 0.2, 0.5])
np.dot(kanto, weights)


56.8

## Operating on Numpy arrays


In [27]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr1 * arr2
arr2.sum()


15

In [29]:
# Python lists
arr1 = list(range(1000000))
arr2 = list(range(1000000, 2000000))

# Numpy arrays
arr1_np = np.array(arr1)
arr2_np = np.array(arr2)

# %%time
np.dot(arr1_np, arr2_np)

-1942957984

## Multi-dimensional Numpy arrays


In [30]:
# 3D array 
arr3 = np.array([
    [[11, 12, 13], 
     [13, 14, 15]], 
    [[15, 16, 17], 
     [17, 18, 19.5]]])
arr3.shape

(2, 2, 3)

## Working with CSV data files


In [3]:
import numpy as np
import requests

import urllib.request

urllib.request.urlretrieve(
    'https://gist.github.com/BirajCoder/a4ffcb76fd6fb221d76ac2ee2b8584e9/raw/4054f90adfd361b7aa4255e99c2e874664094cea/climate.csv', 
    'climate.txt')

('climate.txt', <http.client.HTTPMessage at 0x7fdc3db61e10>)

In [17]:
climate_data = np.genfromtxt('climate.txt',  delimiter = ',',skip_header = 1)
climate_data


array([[25., 76., 99.],
       [39., 65., 70.],
       [59., 45., 77.],
       ...,
       [99., 62., 58.],
       [70., 71., 91.],
       [92., 39., 76.]])

In [18]:
weights = np.array ([0.3, 0.2, 0.5])
yields = climate_data*weights
yields

array([[ 7.5, 15.2, 49.5],
       [11.7, 13. , 35. ],
       [17.7,  9. , 38.5],
       ...,
       [29.7, 12.4, 29. ],
       [21. , 14.2, 45.5],
       [27.6,  7.8, 38. ]])

In [20]:
weights = np.array ([0.3, 0.2, 0.5])
yields = climate_data@weights
yields.shape

(10000,)

### Let's add the yields to climate_data as a fourth column using the np.concatenate function.

In [21]:
climate_results = np.concatenate((climate_data, yields.reshape(10000, 1)), axis=1)
climate_results

array([[25. , 76. , 99. , 72.2],
       [39. , 65. , 70. , 59.7],
       [59. , 45. , 77. , 65.2],
       ...,
       [99. , 62. , 58. , 71.1],
       [70. , 71. , 91. , 80.7],
       [92. , 39. , 76. , 73.4]])

### save data

In [22]:
np.savetxt('climate_results.txt', 
           climate_results, 
           fmt='%.2f', 
           delimiter=',',
           header='temperature,rainfall,humidity,yeild_apples', 
           comments='')

## Array Broadcasting
#### Numpy arrays also support broadcasting, allowing arithmetic operations between two arrays with different numbers of dimensions but compatible shapes.Let's look at an example to see how it works.
#### When the expression arr2 + arr4 is evaluated, arr4 (which has the shape (4,)) is replicated three times to match the shape (3, 4) of arr2. Numpy performs the replication without actually creating three copies of the smaller dimension array, thus improving performance and using lower memory.

In [25]:
arr2 = np.array([[1, 2, 3, 4], 
                 [5, 6, 7, 8], 
                 [9, 1, 2, 3]])
arr2.shape

arr4 = np.array([4, 5, 6, 7])
arr4.shape

arr2 + arr4

array([[ 5,  7,  9, 11],
       [ 9, 11, 13, 15],
       [13,  6,  8, 10]])

### Array Comparison
#### Numpy arrays also support comparison operations like ==, !=, > etc. The result is an array of booleans.

In [28]:
arr1 = np.array([[1, 2, 3], [3, 4, 5]])
arr2 = np.array([[2, 2, 3], [1, 2, 5]])
arr1 == arr2

array([[False,  True,  True],
       [False, False,  True]])

### Array indexing and slicing
#### Numpy extends Python's list indexing notation using [] to multiple dimensions in an intuitive fashion. You can provide a comma-separated list of indices or ranges to select a specific element or a subarray (also called a slice) from a Numpy array.

In [29]:
arr3 = np.array([
    [[11, 12, 13, 14], 
     [13, 14, 15, 19]], 
    
    [[15, 16, 17, 21], 
     [63, 92, 36, 18]], 
    
    [[98, 32, 81, 23],      
     [17, 18, 19.5, 43]]])
arr3.shape

(3, 2, 4)

In [31]:
# Single element
arr3[1, 1, 2]

36.0

In [32]:
# Subarray using ranges
arr3[1:, 0:1, :2]

array([[[15., 16.]],

       [[98., 32.]]])

### Other ways of creating Numpy arrays


In [33]:
# All zeros
np.zeros((3, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [34]:
# All ones
np.ones([2, 2, 3])

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [35]:
# Identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [36]:
# Random vector
np.random.rand(5)

array([0.62696937, 0.33238842, 0.64163823, 0.68640887, 0.47825478])

In [37]:
# Random matrix
np.random.randn(2, 3) # rand vs. randn - what's the difference?

array([[ 0.84317923, -2.39455499,  1.02317863],
       [ 0.01270498, -1.36100011,  0.79270305]])

In [38]:
# Fixed value
np.full([2, 3], 42)

array([[42, 42, 42],
       [42, 42, 42]])

In [39]:
# Range with start, end and step
np.arange(10, 90, 3)

array([10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49, 52, 55, 58,
       61, 64, 67, 70, 73, 76, 79, 82, 85, 88])

In [40]:
# Equally spaced numbers in a range
np.linspace(3, 27, 9)

array([ 3.,  6.,  9., 12., 15., 18., 21., 24., 27.])